baseurl = "https://www.holaenterprise.com"
title = "Create interactive video ads | Hola Enterprise"
languageCode = "en-us"
theme = "base"
disqusShortname = "hola"
[params]
  SiteDescription = "Engage you audience with interactive video ads using Hola Card and benefit from call to action and detailed analytics."
  BlogDescription = "Read about interactive media, animation, hola cards on hola enterprise, world's simplest interactive video creation platform."
  ga_id = "UA-63922413-46"
  crisp_id = "0eeccc97-1a38-4fd0-837b-00de197150ad"
  gmap_key = "AIzaSyCTfaAzvQWSfzJf73ur77d6PdaLro06TcM"
  gmap_height = 250
  gmap_place = "Abda Digital"
  theme_name = "mdb"
  terms_and_conditions_link = "/terms"
  privacy_policy_link = "/privacy"
  year = "2016"
  company_name = "HolaCards"
  copyright_text = "A unit of Abda Digital Pvt. Ltd."
  fb_link = "https://www.facebook.com/Holaenterprise"
  twitter_link = "https://twitter.com/Hola_Card"
  linkdin_link = "https://lnked.in/Holaenterprise"
  [indexes]
      tag = "tags"

[params.portfolio.1]
  category = "hospitals"
  holalink = "https://demo.holacards.com/Vcas/docom_API/84rOy"
  image = "/images/portfolio/reddy.png"
  clienttitle = "Dr Reddy's"
  slidedescription = "Patient Education"
[params.portfolio.2]
  category = "hospitals"
  holalink = "https://demo.holacards.com/Vcas/Medpl_Hi/aCb85"
  image = "/images/portfolio/flexirewards.png"
  clienttitle = "Medplus"
  slidedescription = "Reward points and coupons"
[params.portfolio.3]
  category = "hospitals"
  holalink = "https://demo.holacards.com/Vcas/Conti_API/syNTi"
  image = "/images/portfolio/continental.png"
  clienttitle = "Continental"
  slidedescription = "Book doctor appointment"
[params.portfolio.4]
  category = "food"
  holalink = "https://demo.holacards.com/Vcas/ICICI_broad/HhMGU"
  image = "/images/portfolio/applebees.png"
  clienttitle = "Applebee's"
  slidedescription = "RSVP"
[params.portfolio.20]
  category = "food"
  holalink = "https://demo.holacards.com/Vcas/docom_API/yj5s1"
  image = "/images/portfolio/eggstop.png"
  clienttitle = "Egg stop"
  slidedescription = "Created with Card Designer"
[params.portfolio.5]
  category = "food"
  holalink = "https://demo.holacards.com/Vcas/docom_API/1SOKP"
  image = "/images/portfolio/simplysouth.png"
  clienttitle = "Simply South"
  slidedescription = "Auto play feature"
[params.portfolio.6]
  category = "real"
  holalink = "https://demo.holacards.com/Vcas/Domin_API/w1T05"
  image = "/images/portfolio/lodha.png"
  clienttitle = "Lodha"
  slidedescription = "Special effects with zoom"
[params.portfolio.7]
  category = "real"
  holalink = "https://demo.holacards.com/Vcas/manga_Hi/T5yV6"
  image = "/images/portfolio/mangatari.png"
  clienttitle = "Mangatrai"
  slidedescription = "short animation"
[params.portfolio.8]
  category = "school"
  holalink = "https://demo.holacards.com/Vcas/Espar_API/sqHVQ"
  image = "/images/portfolio/esparanza.png"
  clienttitle = "Esperanza"
  slidedescription = "Layered animation"
[params.portfolio.9]
  category = "telecom"
  holalink = "https://demo.holacards.com/Vcas/Domin_API/jMPPQ"
  image = "/images/portfolio/idea.png"
  clienttitle = "Idea"
  slidedescription = "Change Your Life"
[params.portfolio.10]
  category = "telecom"
  holalink = "https://demo.holacards.com/Vcas/docom_API/K3ldL"
  image = "/images/portfolio/docomo.png"
  clienttitle = "Tata Docomo"
  slidedescription = "Fully interactive Xylophone"
[params.portfolio.11]
  category = "telecom"
  holalink = "https://enterprise.holacards.com/Vcas/ICICI_API/Awxnp"
  image = "/images/portfolio/icici.png"
  clienttitle = "ICICI"
  slidedescription = "Embeded Video Card"
[params.portfolio.12]
  category = "telecom"
  holalink = "https://demo.holacards.com/Vcas/ICICI_API/tl2FL"
  image = "/images/portfolio/grptalk.png"
  clienttitle = "Group Talk"
  slidedescription = "Hand Drawn"
[params.portfolio.13]
  category = "food"
  holalink = "https://demo.holacards.com/Vcas/Domin_broad/Fbe4B"
  image = "/images/portfolio/pizza.png"
  clienttitle = "Pizza Hut"
  slidedescription = "RVSP forms for lead generation"
[params.portfolio.14]
  category = "hospitals"
  holalink = "https://demo.holacards.com/scripts/card.php?id=a0cc230a-11cc-4db3-8a40-c2a3e5926efb"
  image = "/images/portfolio/apollo.png"
  clienttitle = "Rating"
  slidedescription = "Feeback with unique responses"
[params.portfolio.15]
  category = "gulf school"
  holalink = "https://smscountry.enterprise1.holacards.com/he/cr?id=A7vAXeGBu"
  image = "/images/portfolio/gulfuniversity.png"
  clienttitle = "Gulf University"
  slidedescription = "Gulf University"
[params.portfolio.16]
  category = "gulf"
  holalink = "https://smscountry.enterprise1.holacards.com/he/cr?id=Rc1t1uuGB"
  image = "/images/portfolio/hassan.png"
  clienttitle = "Dr Haji Hasan"
  slidedescription = "Dr Haji Hasan"
[params.portfolio.17]
  category = "gulf"
  holalink = "https://demo.holacards.com/he/cr?id=Nvv8Ec6BX"
  image = "/images/portfolio/saarmall.png"
  clienttitle = "Saar Mall"
  slidedescription = "Saar Mall"

[params.portfolio.18]
  category = "gulf"
  holalink = "https://demo.holacards.com/he/cr?id=yCk7vJtXy"
  image = "/images/portfolio/daulbur.png"
  clienttitle = "Diablo Restaurant"
  slidedescription = "Diablo Restaurant"
